version: '3'
services:
  vue-app:
    build:
      context: .  # The context is the directory where your Dockerfile is located.
      dockerfile: Dockerfile  # Specify the path to your Dockerfile.
    ports:
      - "8080:8080"  # Map the container's port to the host machine (change if needed)
    volumes:
      - ./src:/app/src  # Mount your Vue app source code
    command: npm run serve